fruits=[]
f1=input("Enter the string")
fruits.append(f1)
f2=input("Enter the string")
fruits.append(f2)
f3=input("Enter the string")
fruits.append(f3)
f4=input("Enter the string")
fruits.append(f4)
f5=input("Enter the string")
fruits.append(f5)
f6=input("Enter the string")
fruits.append(f6)
fruits.sort()
print(fruits)
